routes/web.php
<?php

use App\Http\Controllers\Bienvenu;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\participant;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\presentation;
use App\Http\Controllers\verification;
use App\Http\Controllers\renduassemble;
use App\Http\Controllers\ClubController;
use App\Http\Controllers\FraisController;
use App\Http\Controllers\AspectController;
use App\Http\Controllers\PaiementController;
use App\Http\Controllers\PersonneController;
use App\Http\Controllers\EvenementController;
use App\Http\Controllers\TableUserController;
use App\Http\Controllers\StatutUserController;
use App\Http\Controllers\AjoutMembreController;
use App\Http\Controllers\PerformanceController;
use App\Http\Controllers\AnneeRotarienneController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* Route::get('/', function () {
    return view('welcomeadmin');
}); */

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('statut-user', StatutUserController::class);

//Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//User
Route::get('/ajoutMembre', [AjoutMembreController::class, 'indexAjoutMembre'])->name('ajoutMembreVue')->middleware('auth');
Route::post('/ajoutMembre',[AjoutMembreController::class, 'ajoutMembre'])->name('ajoutMembre');

Route::get('/tableUser', [TableUserController::class, 'indexTableUser'])->name('indextableUser')->middleware('auth');
Route::put('/supprimerUser/{id}', [TableUserController::class, 'supprimerUser'])->name('supprimerUser');
Route::post('/supprimerUserAll', [TableUserController::class, 'supprimerUserAll'])->name('supprimerUserAll');
Route::post('/supprimerUserAllCocher', [TableUserController::class, 'supprimerUserAllCocher'])->name('supprimerUserAllCocher');
Route::post('/retourAjouter', [TableUserController::class, 'retourAjouter'])->name('retourAjouter');
Route::post('/compteRenduReunion', [TableUserController::class, 'compteRenduReunion'])->name('compteRenduReunion');

Route::get('/evenementPublication', [EvenementController::class, 'evenement'])->name('evenement')->middleware('auth');
Route::post('/evenementPublication', [EvenementController::class, 'evenementPublication'])->name('evenementPublication');

Route::get('/fraisParticipation', [FraisController::class, 'fraisParticipation'])->name('fraisParticipation')->middleware('auth');
Route::post('/fraisParticipation', [FraisController::class, 'ValidationFraisParticipation'])->name('ValidationFraisParticipation');
Route::get('/paiement',[PaiementController::class, 'paiement'])->name('paiement');


//
Route::get('bienvenue', [Bienvenu::class, 'bienvenue']);
Route::get('create', [Bienvenu::class, 'frais']);
//Route::resource('frais', FraisController::class);
Route::resource('statut-user', StatutUserController::class)->middleware('auth');
Route::get('bienvenue', [Bienvenu::class, 'bienvenue'])->name('bienvenue')->middleware('auth');
Route::get('create', [Bienvenu::class, 'frais'])->middleware('auth');
//Route::resource('frais', FraisController::class)->middleware('auth');
Route::resource('frais', FraisController::class)->middleware('auth');
Route::post('personne/connexion', [PersonneController::class, 'verification'])->name('loginconnexion');
Route::resource('personne', PersonneController::class)/* ->middleware('auth') */;
Route::get('personne/desable/{id}', [PersonneController::class, 'disable'])->name('person.desable')->middleware('auth');
Route::resource('club', ClubController::class)/* ->middleware('auth') */;
Route::resource('anneerotarienne', AnneeRotarienneController::class)->middleware('auth');
Route::resource('performance', PerformanceController::class)->middleware('auth');
Route::resource('aspect', AspectController::class)->middleware('auth');
Route::get('rotary', [presentation::class, 'rotary']);
Route::get('interact', [presentation::class, 'interact']);
Route::get('district9102', [presentation::class, 'district9102']);
Route::get('ryla', [presentation::class, 'ryla']);
Route::get('acd', [presentation::class, 'acd']);
Route::post('seconnecter', [verification::class, 'verification'])->name('seconnecter');
Route::get('compterenduassemble', [renduassemble::class, 'create']);
Route::get('personnepresente', [participant::class, 'create']);

app/Http/Controllers/PersonneController.php
<?php

namespace App\Http\Controllers;

use App\Models\Club;
use App\Models\User;
use App\Models\Membre;
use App\Models\Personne;
use App\Models\TypeUser;
use App\Models\StatutUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\QueryException;

class PersonneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Liste = User::with('statutuser')->get();
        //$DemandesListe = $Liste[0]->statutuser->CodeStatutUser ;
        //dd($Liste);
        //dd($Liste[0]->statutuser);
        //dd($Liste[0]->statutuser->CodeStatutUser);
        return view('personne.index', [
            'listPersonne' => $Liste,
            //'couleur'=>$DemandesListe,
            'listType' => TypeUser::all(),
            'listStatut' => StatutUser::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $date = date('Y-m-d');
        return view('personne.create', compact('date'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nom' => 'required|max:20',
            'prenom' => 'required|max:20',
            'datenaissance' => 'required',
            'email' => 'required|email',
            'password' => 'required|min:8',
            'passwordconfirm' => 'required|min:8',
            'sexe' => 'required',
        ]);

        $typeuser = TypeUser::where('CodeTypeUser', 0)->first();

        $statutuser = StatutUser::where('CodeStatutUser', 0)->first();
        //dd($request->all());
        $date = date('Y-m-d');

        if ($request->datenaissance <= $date) {
            if ($request->password == $request->passwordconfirm) {
                try {
                    $user =   User::make([
                        'Nom' => $request->nom,
                        'Prenom' => $request->prenom,
                        'DateNaissance' => $request->datenaissance,
                        'email' => $request->email,
                        'password' => bcrypt($request->password),
                        'Sexe' => $request->sexe,

                    ]);
                    $user->typeuser()->associate($typeuser);
                    $user->statutuser()->associate($statutuser);
                    $user->save();
                    return back()->with('successMessage', "La personne [" . $request->nom .' '. $request->prenom . "] a été crée avec succès");
                } catch (QueryException $ex) {
                    return back()->with('errorMessage', "Echec de la création de [" . $request->nom .' '. $request->prenom . "]");
                }
            } else {
                return back()->with('errorMessage', "Echec de la création de [" . $request->nom .' '. $request->prenom . "]");
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Personne  $personne
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Personne  $personne
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $personne = User::find($id);
        if ($personne)
            return view('personne.show', [
                'listPersonne' => $personne,
                'listStatut' => StatutUser::all()
            ]);
        else
            return redirect(route('personne.index'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Personne  $personne
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nom' => 'required|max:20',
            'prenom' => 'required|max:20',
            'datenaissance' => 'required',
            'email' => 'required|email',
            'password' => 'required|min:8',
            'sexe' => 'required',
        ]);
        $typeuser = TypeUser::where('CodeTypeUser', 0)->first();
        //dd($typeuser->id);
        //dd($request->libelle);

        try {
            $currentData = User::find($id);
            $currentData->Nom = $request->nom;
            $currentData->Prenom = $request->prenom;
            $currentData->DateNaissance = $request->datenaissance;
            $currentData->Sexe = $request->sexe;
            $currentData->email = $request->email;
            $currentData->password = bcrypt($request->password);
            $currentStatut = StatutUser::find($request->libelle);
            $currentData->statutuser()->associate($currentStatut);
            $currentData->save();
            return back()->with('successMessage', "Les informations de [" . $request->nom . $request->prenom . "] ont été modifiée avec succès");
        } catch (QueryException $ex) {
            return back()->with('errorMessage', "Echec de la modification de [" . $request->nom . $request->prenom . "]");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Personne  $personne
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $statutuser = StatutUser::where('CodeStatutUser', 0)->first();

        try {
            $currentData = User::find($id);
            //$currentStatut = StatutUser::find($request->libelle);
            $currentData->statutuser()->associate($statutuser->id);
            $currentData->save();
            return back()->with('successMessage', "Le membre a été désactiver avec succès");
        } catch (QueryException $ex) {
            return back()->with('errorMessage', "Echec de la désactivation");
        }
    }

    public function disable($id)
    {
        //dd($id);
        $statutuser = StatutUser::where('CodeStatutUser', 1)->first();
        //dd($statutuser->id);

        try {
            $currentData = User::find($id);
            //$currentStatut = StatutUser::find($request->libelle);
            $currentData->statutuser()->associate($statutuser->id);
            $currentData->save();
            return back()->with('successMessage', "Le membre a été désactiver avec succès");
        } catch (QueryException $ex) {
            return back()->with('errorMessage', "Echec de la désactivation");
        }
    }

    public function verification(Request $request)
    {
        $request->validate([
            'email'=>'required|email',
            'password'=>'required',
            'nomClub'=>'required'
        ]);

        if( Auth::attempt(['email' => $request->email, 'password' => $request->password]))
        {
            $user = Auth::user();
            $club = Club::findorFail($request->nomClub);
            $membre = Membre::where('PersonneId', $user->id)
            ->where('ClubId', $club->id)->first();
            if (!is_null($membre) ) {
                $request->session()->put('idclub', $club->id);
                return redirect()->route('bienvenue');
            } else {
                Auth::logout();
                return back()->with('errorMessage', "Vos informations ne sont pas correctes");
            }

        }


    }
}

resources/views/personne/create.blade.php
@extends('layouts.dashboard')

@section('content')
@if (session()->has('successMessage'))
            <div class="alert alert-success" role="alert">
                {{ session('successMessage') }}
            </div>
        @endif
        @if (session()->has('errorMessage'))
            <div class="alert alert-danger" role="alert">
                {{ session('errorMessage') }}
            </div>
        @endif
<form class="form-horizontal row-fluid" action="{{route('personne.store')}}" method="POST">
    @csrf
    <div class="control-group">
        <label class="control-label" for="basicinput">Nom</label>
        <div class="controls">
            <input type="text" name="nom" id="basicinput"  class="span8" style="width: 50%">
            <span class="help-inline">Maximum 20 caractères</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Prénom</label>
        <div class="controls">
            <input type="text" name="prenom" id="basicinput"  class="span8" style="width: 50%">
            <span class="help-inline">Maximum 20 caractères</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Date de naissance</label>
        <div class="controls">
            <input type="date" name="datenaissance" id="basicinput"  class="span8" style="width: 50%" max="{{$date}}">
            <span class="help-inline"></span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Email</label>
        <div class="controls">
            <input type="email" name="email" id="basicinput"  class="span8" style="width: 50%">
            <span class="help-inline"></span>
        </div>
        @error('email') <span class="text-danger" role="alert"> {{ $message }}</span>
                @enderror
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Sexe : </label>
        <div class="controls">
            <div class="dropdown">
                <select id="sexe" name="sexe"
                    class="form-control select2  sexe @error('sexe') is-invalid @enderror" data-plugin="select2"
                    style="width: 50%">
                    <option value="">Veuillez selectionner le sexe</option>
                    <option value="M">Masculin | M</option>
                    <option value="F">Féminin | F</option>
                </select>
                @error('libelle') <span class="text-danger" role="alert"> {{ $message }}</span>
                @enderror

            </div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Mot de passe</label>
        <div class="controls">
            <input type="password" name="password" id="basicinput"  class="span8" style="width: 50%">
            <span class="help-inline">Minimum 8 caractères</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Confirmer le mot de passe</label>
        <div class="controls">
            <input type="password" name="passwordconfirm" id="basicinput"  class="span8" style="width: 50%">
            <span class="help-inline">Minimum 8 caractères</span>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn" style="background: greenyellow">Valider</button>
        </div>
    </div>
</form>
@endsection

resources/views/personne/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="module">
    <div class="module-head">
        <h3>
            Liste des personnes du club</h3>
    </div>
    <div class="module-body table">
        <table cellpadding="0" cellspacing="0" border="0"
            class="datatable-1 table table-bordered table-striped	 display" width="100%">
            <thead>
                <tr>
                    <th>
                        Nom
                    </th>
                    <th>
                        Prénom
                    </th>
                    <th>
                        Sexe
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        Date de naissance
                    </th>
                    <th>

                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach ($listPersonne as $item)
                <tr class="odd gradeX">
                    <td>
                        {{ $item->Nom }}
                    </td>
                    <td>
                        {{ $item->Prenom }}
                    </td>
                    <td>
                        {{ $item->Sexe }}
                    </td>
                    <td class="center">
                        {{ $item->email }}
                    </td>
                    <td class="center">
                        {{ $item->DateNaissance }}
                    </td>
                    <td >
                        @if ($item->statutuser->CodeStatutUser == 0)
                        <a id="btnEdit"  title="Modifier" ><i class="fa fa-circle" style="color: green"></i></a>
                        @else
                        <a id="btnEdit"  title="Modifier" ><i class="fa fa-circle" style="color: red"></i></a>
                        @endif
                        {{-- <a id="btnEdit"  title="Modifier" ><i class="fa fa-circle" style="color: red"></i></a>
                        <a id="btnEdit"  title="Modifier" ><i class="fa fa-circle" style="color: green"></i></a> --}}
                    </td>
                    <td>
                        <a id="btnEdit"  title="Modifier" href="{{ route('personne.edit', $item->id) }}"><i
                                class="fa fa-pencil text-default"></i></a>&nbsp; &nbsp; &nbsp;

                        <a id="btnDelete" title="Supprimer"
                            href="{{route('person.desable', ['id' =>$item->id]) }}"><i class="fa fa-power-off" style="color: rgb(220,20,60)"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>


@endsection

resources/views/personne/show.blade.php
@extends('layouts.dashboard')

@section('content')
@if (session()->has('successMessage'))
            <div class="alert alert-success" role="alert">
                {{ session('successMessage') }}
            </div>
        @endif
        @if (session()->has('errorMessage'))
            <div class="alert alert-danger" role="alert">
                {{ session('errorMessage') }}
            </div>
        @endif
<form class="form-horizontal row-fluid" action="{{route('personne.update', $listPersonne->id)}}" method="POST">
    @csrf
    @method('PUT')
    <div class="control-group">
        <label class="control-label" for="basicinput">Nom</label>
        <div class="controls">
            <input type="text" name="nom" id="basicinput" value="{{$listPersonne->Nom}}"  class="span8" style="width: 50%">
            <span class="help-inline">Maximum 20 caractères</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Prénom</label>
        <div class="controls">
            <input type="text" name="prenom" id="basicinput" value="{{$listPersonne->Prenom}}"  class="span8" style="width: 50%">
            <span class="help-inline">Maximum 20 caractères</span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Date de naissance</label>
        <div class="controls">
            <input type="date" name="datenaissance" id="basicinput" value="{{$listPersonne->DateNaissance}}"  class="span8" style="width: 50%" >
            <span class="help-inline"></span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Email</label>
        <div class="controls">
            <input type="email" name="email" value="{{$listPersonne->email}}" id="basicinput"  class="span8" style="width: 50%">
            <span class="help-inline"></span>
        </div>
        @error('email') <span class="text-danger" role="alert"> {{ $message }}</span>
                @enderror
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Sexe : </label>
        <div class="controls">
            <div class="dropdown">
                <select id="sexe" name="sexe"
                    class="form-control select2  sexe @error('sexe') is-invalid @enderror" data-plugin="select2"
                    style="width: 50%">
                    <option value="">Veuillez selectionner le sexe</option>
                    <option value="M">Masculin | M</option>
                    <option value="F">Féminin | F</option>
                </select>
                @error('libelle') <span class="text-danger" role="alert"> {{ $message }}</span>
                @enderror

            </div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Statut de la personne : </label>
        <div class="controls">
            <div class="dropdown">
                <select id="libelle" name="libelle"
                    class="form-control select2  libelle @error('libelle') is-invalid @enderror" data-plugin="select2"
                    style="width: 25%">
                    <option value="">Veuillez selectionner</option>
                    @foreach ($listStatut as $item)
                    <option value="{{ $item->id }}">
                        {{ $item->Libelle }}
                    </option>
                    @endforeach
                </select>
                @error('libelle') <span class="text-danger" role="alert"> {{ $message }}</span>
                @enderror

            </div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Mot de passe</label>
        <div class="controls">
            <input type="text" name="password" value="{{$listPersonne->password}}" id="basicinput"  class="span8" style="width: 50%">
            <span class="help-inline">Minimum 8 caractères</span>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn" style="background: greenyellow">Valider</button>
        </div>
    </div>
</form>
@endsection