routes/web.php
<?php

use App\Http\Controllers\Bienvenu;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\participant;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\presentation;
use App\Http\Controllers\verification;
use App\Http\Controllers\renduassemble;
use App\Http\Controllers\ClubController;
use App\Http\Controllers\FraisController;
use App\Http\Controllers\AspectController;
use App\Http\Controllers\PaiementController;
use App\Http\Controllers\PersonneController;
use App\Http\Controllers\EvenementController;
use App\Http\Controllers\TableUserController;
use App\Http\Controllers\StatutUserController;
use App\Http\Controllers\AjoutMembreController;
use App\Http\Controllers\PerformanceController;
use App\Http\Controllers\AnneeRotarienneController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* Route::get('/', function () {
    return view('welcomeadmin');
}); */

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('statut-user', StatutUserController::class);

//Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//User
Route::get('/ajoutMembre', [AjoutMembreController::class, 'indexAjoutMembre'])->name('ajoutMembreVue')->middleware('auth');
Route::post('/ajoutMembre',[AjoutMembreController::class, 'ajoutMembre'])->name('ajoutMembre');

Route::get('/tableUser', [TableUserController::class, 'indexTableUser'])->name('indextableUser')->middleware('auth');
Route::put('/supprimerUser/{id}', [TableUserController::class, 'supprimerUser'])->name('supprimerUser');
Route::post('/supprimerUserAll', [TableUserController::class, 'supprimerUserAll'])->name('supprimerUserAll');
Route::post('/supprimerUserAllCocher', [TableUserController::class, 'supprimerUserAllCocher'])->name('supprimerUserAllCocher');
Route::post('/retourAjouter', [TableUserController::class, 'retourAjouter'])->name('retourAjouter');
Route::post('/compteRenduReunion', [TableUserController::class, 'compteRenduReunion'])->name('compteRenduReunion');

Route::get('/evenementPublication', [EvenementController::class, 'evenement'])->name('evenement')->middleware('auth');
Route::post('/evenementPublication', [EvenementController::class, 'evenementPublication'])->name('evenementPublication');

Route::get('/fraisParticipation', [FraisController::class, 'fraisParticipation'])->name('fraisParticipation')->middleware('auth');
Route::post('/fraisParticipation', [FraisController::class, 'ValidationFraisParticipation'])->name('ValidationFraisParticipation');
Route::get('/paiement',[PaiementController::class, 'paiement'])->name('paiement');


//
Route::get('bienvenue', [Bienvenu::class, 'bienvenue']);
Route::get('create', [Bienvenu::class, 'frais']);
//Route::resource('frais', FraisController::class);
Route::resource('statut-user', StatutUserController::class)->middleware('auth');
Route::get('bienvenue', [Bienvenu::class, 'bienvenue'])->name('bienvenue')->middleware('auth');
Route::get('create', [Bienvenu::class, 'frais'])->middleware('auth');
//Route::resource('frais', FraisController::class)->middleware('auth');
Route::resource('frais', FraisController::class)->middleware('auth');
Route::post('personne/connexion', [PersonneController::class, 'verification'])->name('loginconnexion');
Route::resource('personne', PersonneController::class)/* ->middleware('auth') */;
Route::get('personne/desable/{id}', [PersonneController::class, 'disable'])->name('person.desable')->middleware('auth');
Route::resource('club', ClubController::class)/* ->middleware('auth') */;
Route::resource('anneerotarienne', AnneeRotarienneController::class)->middleware('auth');
Route::resource('performance', PerformanceController::class)->middleware('auth');
Route::resource('aspect', AspectController::class)->middleware('auth');
Route::get('rotary', [presentation::class, 'rotary']);
Route::get('interact', [presentation::class, 'interact']);
Route::get('district9102', [presentation::class, 'district9102']);
Route::get('ryla', [presentation::class, 'ryla']);
Route::get('acd', [presentation::class, 'acd']);
Route::post('seconnecter', [verification::class, 'verification'])->name('seconnecter');
Route::get('compterenduassemble', [renduassemble::class, 'create']);
Route::get('personnepresente', [participant::class, 'create']);

app/Models/AnneeRotarienne.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class AnneeRotarienne extends Model
{
    use HasFactory;
    protected $table= 'AnneeRotarienne';

    protected $fillable = [
        'Date1',
        'Date2'
    ];

    public function performance ()
    {
        return $this->belongsToMany(Performance::class,'Relier', 'AnneeRotarienneId', 'PerformanceId');
    }
}

app/Http/Controllers/AnneeRotarienneController.php
<?php

namespace App\Http\Controllers;

use App\Models\AnneeRotarienne;
use App\Models\Relier;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;

class AnneeRotarienneController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('anneerotarienne.index', [
            'listAnnee'=> AnneeRotarienne::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('anneerotarienne.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd('ff');
        $request->validate([
            'date1' => 'required|date',
            'date2' => 'required|date',
        ]);
        //dd($request->date1);

        if ($request->date1>=$request->date2) {
            return back()->with('errorMessage', "Période non valide");
        } else {
            try {
                AnneeRotarienne::create([
                    'Date1'=>$request->date1,
                    'Date2'=>$request->date2
                ]);
                return back()->with('successMessage', "Date crée");
            } catch (QueryException $ex) {
                return back()->with('errorMessage', "Date non crée");
            }
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\AnneeRotarienne  $anneeRotarienne
     * @return \Illuminate\Http\Response
     */
    public function show(AnneeRotarienne $anneeRotarienne)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\AnneeRotarienne  $anneeRotarienne
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $annee = AnneeRotarienne::find($id);
        return view('anneerotarienne.show', [
            'listAnnee'=>$annee
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\AnneeRotarienne  $anneeRotarienne
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'date1'=>'required|date',
            'date2'=>'required|date'
        ]);

        try {
            $currentData = AnneeRotarienne::find($id);
            $currentData ->Date1 = $request->date1;
            $currentData->Date2 = $request->date2;
            $currentData->save();
            return back()->with('successMessage', "Date modifiée");

        } catch (QueryException $ex) {
            return back()->with('errorMessage', "Erreur, date non modifiée");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\AnneeRotarienne  $anneeRotarienne
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        dd('ffff');
        $annee = Relier::find($id);
        if ($annee) {
            return back()->with('errorMessage', "Impossible de supprimer cette date, Liaison avec d'autres tables");
        } else {
            AnneeRotarienne::destroy($id);
            return back()->with('successMessage', "La date a été supprimer avec succès");
        }

    }
}

resources/views/anneerotarienne/create.blade.php
@extends('layouts.dashboard')

@section('content')
@if (session()->has('successMessage'))
            <div class="alert alert-success" role="alert">
                {{ session('successMessage') }}
            </div>
        @endif
        @if (session()->has('errorMessage'))
            <div class="alert alert-danger" role="alert">
                {{ session('errorMessage') }}
            </div>
        @endif
<form class="form-horizontal row-fluid" action="{{route('anneerotarienne.store')}}" method="POST">
    @csrf
    <div class="control">
        <label for="">Merci</label>
    </div>
    <div>
        <label class="control-label" for="basicinput"></label>
        <div class="controls">
            <span><b>Du : </b></span>
            <span style="margin-left:27%;"><b>Au :</b></span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Année rotarienne</label>
        <div class="controls">
            <input type="date" name="date1" id="basicinput"  class="span8" style="width: 30%" >
            <input type="date" name="date2" id="basicinput"  class="span8" style="width: 30%" >
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn" style="background: greenyellow">Valider</button>
        </div>
    </div>
</form>
@endsection

resources/views/anneerotarienne/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="module">
    <div class="module-head">
        <h3>
            Liste des personnes du club</h3>
    </div>
    <div class="module-body table">
        <table cellpadding="0" cellspacing="0" border="0"
            class="datatable-1 table table-bordered table-striped	 display" width="100%">
            <thead>
                <tr>
                    <th>
                        Date début période
                    </th>
                    <th>
                        Date fin période
                    </th>
                    <th style="text-align:right">

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach ($listAnnee as $item)
                <tr class="odd gradeX">
                    <td>
                        {{ $item->Date1 }}
                    </td>
                    <td>
                        {{ $item->Date2 }}
                    </td>
                    <td style="text-align:right">
                        <a id="btnEdit"  title="Modifier" href="{{ route('anneerotarienne.edit', $item->id) }}"><i
                                class="fa fa-pencil text-default"></i></a>&nbsp; &nbsp; &nbsp;

                                <a id="btnDelete" title="Supprimer"
                                href="{{ route('anneerotarienne.destroy', $item->id) }}"><i class="fa fa-power-off" style="color: rgb(220,20,60)"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>


@endsection

resources/views/anneerotarienne/show.blade.php
@extends('layouts.dashboard')

@section('content')
@if (session()->has('successMessage'))
            <div class="alert alert-success" role="alert">
                {{ session('successMessage') }}
            </div>
        @endif
        @if (session()->has('errorMessage'))
            <div class="alert alert-danger" role="alert">
                {{ session('errorMessage') }}
            </div>
        @endif
<form class="form-horizontal row-fluid" action="{{route('anneerotarienne.update', $listAnnee->id)}}" method="POST">
    @csrf
    @method('PUT')
    <div class="control">
        <label for="">Merci</label>
    </div>
    <div>
        <label class="control-label" for="basicinput"></label>
        <div class="controls">
            <span><b>Du : </b></span>
            <span style="margin-left:27%;"><b>Au :</b></span>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Année rotarienne</label>
        <div class="controls">
            <input type="date" name="date1" id="basicinput" value="{{$listAnnee->Date1}}"  class="span8" style="width: 30%" >
            <input type="date" name="date2" id="basicinput" value="{{$listAnnee->Date2}}"  class="span8" style="width: 30%" >
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn" style="background: greenyellow">Valider</button>
        </div>
    </div>
</form>
@endsection