routes/web.php
<?php

use App\Http\Controllers\Bienvenu;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\participant;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\presentation;
use App\Http\Controllers\verification;
use App\Http\Controllers\renduassemble;
use App\Http\Controllers\ClubController;
use App\Http\Controllers\FraisController;
use App\Http\Controllers\AspectController;
use App\Http\Controllers\PaiementController;
use App\Http\Controllers\PersonneController;
use App\Http\Controllers\EvenementController;
use App\Http\Controllers\TableUserController;
use App\Http\Controllers\StatutUserController;
use App\Http\Controllers\AjoutMembreController;
use App\Http\Controllers\PerformanceController;
use App\Http\Controllers\AnneeRotarienneController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* Route::get('/', function () {
    return view('welcomeadmin');
}); */

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('statut-user', StatutUserController::class);

//Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//User
Route::get('/ajoutMembre', [AjoutMembreController::class, 'indexAjoutMembre'])->name('ajoutMembreVue')->middleware('auth');
Route::post('/ajoutMembre',[AjoutMembreController::class, 'ajoutMembre'])->name('ajoutMembre');

Route::get('/tableUser', [TableUserController::class, 'indexTableUser'])->name('indextableUser')->middleware('auth');
Route::put('/supprimerUser/{id}', [TableUserController::class, 'supprimerUser'])->name('supprimerUser');
Route::post('/supprimerUserAll', [TableUserController::class, 'supprimerUserAll'])->name('supprimerUserAll');
Route::post('/supprimerUserAllCocher', [TableUserController::class, 'supprimerUserAllCocher'])->name('supprimerUserAllCocher');
Route::post('/retourAjouter', [TableUserController::class, 'retourAjouter'])->name('retourAjouter');
Route::post('/compteRenduReunion', [TableUserController::class, 'compteRenduReunion'])->name('compteRenduReunion');

Route::get('/evenementPublication', [EvenementController::class, 'evenement'])->name('evenement')->middleware('auth');
Route::post('/evenementPublication', [EvenementController::class, 'evenementPublication'])->name('evenementPublication');

Route::get('/fraisParticipation', [FraisController::class, 'fraisParticipation'])->name('fraisParticipation')->middleware('auth');
Route::post('/fraisParticipation', [FraisController::class, 'ValidationFraisParticipation'])->name('ValidationFraisParticipation');
Route::get('/paiement',[PaiementController::class, 'paiement'])->name('paiement');


//
Route::get('bienvenue', [Bienvenu::class, 'bienvenue']);
Route::get('create', [Bienvenu::class, 'frais']);
//Route::resource('frais', FraisController::class);
Route::resource('statut-user', StatutUserController::class)->middleware('auth');
Route::get('bienvenue', [Bienvenu::class, 'bienvenue'])->name('bienvenue')->middleware('auth');
Route::get('create', [Bienvenu::class, 'frais'])->middleware('auth');
//Route::resource('frais', FraisController::class)->middleware('auth');
Route::resource('frais', FraisController::class)->middleware('auth');
Route::post('personne/connexion', [PersonneController::class, 'verification'])->name('loginconnexion');
Route::resource('personne', PersonneController::class)/* ->middleware('auth') */;
Route::get('personne/desable/{id}', [PersonneController::class, 'disable'])->name('person.desable')->middleware('auth');
Route::resource('club', ClubController::class)/* ->middleware('auth') */;
Route::resource('anneerotarienne', AnneeRotarienneController::class)->middleware('auth');
Route::resource('performance', PerformanceController::class)->middleware('auth');
Route::resource('aspect', AspectController::class)->middleware('auth');
Route::get('rotary', [presentation::class, 'rotary']);
Route::get('interact', [presentation::class, 'interact']);
Route::get('district9102', [presentation::class, 'district9102']);
Route::get('ryla', [presentation::class, 'ryla']);
Route::get('acd', [presentation::class, 'acd']);
Route::post('seconnecter', [verification::class, 'verification'])->name('seconnecter');
Route::get('compterenduassemble', [renduassemble::class, 'create']);
Route::get('personnepresente', [participant::class, 'create']);

app/Models/Club.php
<?php

namespace App\Models;

use App\Models\CategorieAction;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Club extends Model
{
    use HasFactory;
    protected $table= 'Club';

    protected $fillable = [
        //'IdResponsable',
        'NomClub',
        'Historique',
        'ActionFM',

    ];

    public function personneresponsable ()
    {
        return $this->belongsTo(User::class, 'ResponsableId');
    }

    public function personne ()
    {
        return $this->belongsToMany(User::class,  'Membre','ClubId', 'PersonneId');
    }

    public function frais ()
    {
        return $this->belongsToMany(Frais::class, 'FraisId');
    }

    public function pays ()
    {
        return $this->belongsTo(Pays::class, 'PaysId');
    }

    public function performance ()
    {
        return $this->belongsToMany(Performance::class,'Relier','ClubId', 'PerformanceId');
    }

    public function categorie ()
    {
        return $this->belongsTo(CategorieAction::class, 'CategorieId');
    }

    public function evenementconjoint ()
    {
        return $this->belongsToMany(Evenement::class, 'ClubConjoint', 'EvenementId', 'ClubId');
    }
}

app/Http/Controllers/ClubController.php
<?php

namespace App\Http\Controllers;

use App\Models\Club;
use App\Models\Pays;
use App\Models\Role;
use App\Models\User;
use App\Models\Aspect;
use App\Models\CategorieAction;
use App\Models\Membre;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\QueryException;
use Symfony\Component\Console\Input\Input;

class ClubController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        /* $user = DB::table('Membre')
                ->join('Personne', 'Personne.id', '=', 'Membre.PersonneId')
                ->join('Club', 'Club.id', '=', 'Membre.ClubId')
                ->select('Membre.*', 'Personne.*', 'Club.*')
                ->get();
        dd($user); */

        $club = Club::with('personneresponsable')->get();
        //dd($club);
        return view('club.index', [
            'listClub' =>$club
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        return view('club.create', [
            'personneList' => User::all(),
            'paysList' => Pays::all(),
            'categorieList'=>CategorieAction::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd('dddd');
        $request->validate([
            'nomclub' => 'required|max:20|unique:Club,NomClub,',
            'nomResponsable' => 'required',
            'actionfm' => 'required|max:50',
            'historique' => 'required|max:50',
            'nomPays' => 'required',
            'nomCategorie'=>'required'
        ]);
        //dd((int)$request->nomResponsable);

        try {
            $club = Club::make([
                //'PersonneId' => (int)$request->nomResponsable,
                'NomClub' => $request->nomclub,
                'Historique' => $request->historique,
                'ActionFM' => $request->actionfm,
                //'PaysId' => (int)$request->nomPays
            ]);
            $club->pays()->associate((int)$request->nomPays);
            $club->personneresponsable()->associate((int)$request->nomResponsable);
            $club->categorie()->associate($request->nomCategorie);
            $club->save();
        } catch (QueryException $ex) {
            return back()->with('errorMessage', "Echec de la création du club [".$request->nomclub."]");
        }

        $role = Role::where('CodeRole', 0)->first();

        $membre = new Membre();
        $membre ->ClubId = $club->id;
        $membre ->PersonneId = (int)$request->nomResponsable;
        $membre->DateAdhesion = date('Y-m-d');
        $membre->RoleId =$role->id;
        $membre->save();
        return back()->with('successMessage', "Le Club [".$request->nomclub."] a été crée avec succès");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Club  $club
     * @return \Illuminate\Http\Response
     */
    public function show(Club $club)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Club  $club
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $club = Club::find($id);

        $clubpersonne = Club::where('id', $id)->with('personneresponsable', 'pays')->first();
        //$clubpersonne = User::where('id', $id)->with('club')->first();
        //dd($clubpersonne);

        return view('club.show', [
            'listClub'=>$clubpersonne,
            'listPersonne'=>User::all()
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Club  $club
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nomclub'=>'required|max:20',
            'nomResponsable'=>'required',
            'actionfm'=>'required|max:20'
        ]);
        try {
        $currentData = Club::find($id);
        $currentData->NomClub = $request->nomclub;
        $currentData->personneresponsable()->associate((int)$request->nomResponsable);
        $currentData->ActionFM = $request->actionfm;
        $currentData->save();
        return back()->with('successMessage', "Le club [" . $request->nomclub. "] ont été modifié avec succès");
        } catch (QueryException $ex) {
            return back()->with('errorMessage', "Echec de la modification du club [" . $request->nomclub. "]");
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Club  $club
     * @return \Illuminate\Http\Response
     */
    public function destroy(Club $club)
    {
        //
    }


}

resources/views/club/create.blade.php
@extends('layouts.dashboard')

@section('content')
@if (session()->has('successMessage'))
            <div class="alert alert-success" role="alert">
                {{ session('successMessage') }}
            </div>
        @endif
        @if (session()->has('errorMessage'))
            <div class="alert alert-danger" role="alert">
                {{ session('errorMessage') }}
            </div>
        @endif
<form class="form-horizontal row-fluid" action="{{route('club.store')}}" method="POST">
    @csrf
    <div class="control-group">
        <label class="control-label" for="basicinput">Nom du club</label>
        <div class="controls">
            <input type="text" name="nomclub" id="basicinput"  class="span8" style="width: 50%">
            <span class="help-inline">Maximum 20 caractères</span>
        </div>
        @error('nomclub') <span class="text-danger">{{ $errors->first('nomclub') }}</span> @enderror
        <span class="focus-input100"></span>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Responsable du club : </label>
        <div class="controls">
            <div class="dropdown">
                <select id="nomResponsable" name="nomResponsable" style="width: 50%"
                    class="form-control select2  nomResponsable @error('nomResponsable') is-invalid @enderror" data-plugin="select2"
                    style="width: 25%">
                    <option value="">Veuillez selectionner le responsable</option>
                    @foreach ($personneList as $item)
                    <option value="{{ $item->id }}">
                        {{ $item->Prenom }} {{$item->Nom}}
                    </option>
                    @endforeach
                </select>
                @error('nomResponsable') <span class="text-danger" role="alert"> {{ $message }}</span>
                @enderror

            </div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Catégorie : </label>
        <div class="controls">
            <div class="dropdown">
                <select id="nomCategorie" name="nomCategorie" style="width: 50%"
                    class="form-control select2  nomCategorie @error('nomCategorie') is-invalid @enderror" data-plugin="select2"
                    style="width: 25%">
                    <option value="">Veuillez selectionner la catégorie</option>
                    @foreach ($categorieList as $item)
                    <option value="{{ $item->id }}">
                        {{ $item->Libelle }}
                    </option>
                    @endforeach
                </select>
                @error('nomCategorie') <span class="text-danger" role="alert"> {{ $message }}</span>
                @enderror

            </div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Pays</label>
        <div class="controls">
            <div class="dropdown">
                <select id="nomPays" name="nomPays" style="width: 50%"
                    class="form-control select2  nomPays @error('nomPays') is-invalid @enderror" data-plugin="select2"
                    style="width: 25%">
                    <option value="">Veuillez selectionner le pays</option>
                    @foreach ($paysList as $item)
                    <option value="{{ $item->id }}">
                        {{ $item->Intitule }}
                    </option>
                    @endforeach
                </select>
                @error('nomPays') <span class="text-danger" role="alert"> {{ $message }}</span>
                @enderror

            </div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Action FM</label>
        <div class="controls">
            <input type="text" name="actionfm" id="basicinput"  class="span8" style="width: 50%">
            <span class="help-inline">Maximum 50 caractères</span>
        </div>
        @error('nomclub') <span class="text-danger">{{ $errors->first('nomclub') }}</span> @enderror
        <span class="focus-input100"></span>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Historique</label>
        <div class="controls">
            <textarea name="historique" id="historique" cols="10" rows="10" style="margin: 0px; height: 39px; width: 331px;"></textarea>
            <span class="help-inline">Maximum 50 caractères</span>
        </div>
        @error('nomclub') <span class="text-danger">{{ $errors->first('nomclub') }}</span> @enderror
        <span class="focus-input100"></span>
    </div>


    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn" style="background: greenyellow">Valider</button>
        </div>
    </div>
</form>
<script>

</script>
@endsection

resources/views/club/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="module">
    <div class="module-head">
        <h3>
            Liste des clubs</h3>
    </div>
    <div class="module-body table">
        <table cellpadding="0" cellspacing="0" border="0"
            class="datatable-1 table table-bordered table-striped	 display" width="100%">
            <thead>
                <tr>
                    <th>
                        Club
                    </th>
                    <th>
                        Responsable
                    </th>
                    <th>
                        Historique
                    </th>
                    <th>
                        Action FM
                    </th>
                    <th>
                        Pays
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach ($listClub as $item)
                <tr class="odd gradeX">
                    <td>
                        {{ $item->NomClub }}
                    </td>
                    <td>
                        {{ $item->personneresponsable->Nom }} {{ $item->personneresponsable->Prenom }}
                    </td>
                    <td>
                        {{ $item->Historique }}
                    </td>
                    <td class="center">
                        {{ $item->ActionFM }}
                    </td>
                    <td class="center">
                        {{ $item->pays->Intitule }}
                    </td>
                    <td>
                        <a id="btnEdit"  title="Modifier" href="{{ route('club.edit', $item->id) }}"><i
                                class="fa fa-pencil text-default"></i></a>&nbsp; &nbsp; &nbsp;

                        <a id="btnDelete" title="Supprimer"
                            href="{{ $item->id }}"><i class="fa fa-power-off" style="color: rgb(220,20,60)"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>


@endsection

resources/views/club/show.blade.php
@extends('layouts.dashboard')

@section('content')
@if (session()->has('successMessage'))
            <div class="alert alert-success" role="alert">
                {{ session('successMessage') }}
            </div>
        @endif
        @if (session()->has('errorMessage'))
            <div class="alert alert-danger" role="alert">
                {{ session('errorMessage') }}
            </div>
        @endif
<form class="form-horizontal row-fluid" action="{{route('club.update', $listClub->id)}}" method="POST">
    @csrf
    @method('PUT')
    <div class="control-group">
        <label class="control-label" for="basicinput">Nom du club</label>
        <div class="controls">
            <input type="text" name="nomclub" id="basicinput" value="{{$listClub->NomClub}}"  class="span8" style="width: 50%">
            <input type="text" disabled value="{{$listClub->personneresponsable->Nom}} {{$listClub->personneresponsable->Prenom}}">
        </div>
        @error('nomclub') <span class="text-danger">{{ $errors->first('nomclub') }}</span> @enderror
        <span class="focus-input100"></span>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Responsable du club : </label>
        <div class="controls">
            <div class="dropdown">
                <select id="nomResponsable" name="nomResponsable" style="width: 50%"
                    class="form-control select2  nomResponsable @error('nomResponsable') is-invalid @enderror" data-plugin="select2"
                    style="width: 25%">
                    <option value="">Veuillez selectionner le responsable</option>
                    @foreach ($listPersonne as $item)
                    <option value="{{ $item->id }}">
                        {{ $item->Prenom }} {{$item->Nom}}
                    </option>
                    @endforeach
                </select>
                @error('nomResponsable') <span class="text-danger" role="alert"> {{ $message }}</span>
                @enderror

            </div>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Pays</label>
        <div class="controls">
            <input type="text" disabled name="nompays" id="basicinput" value="{{$listClub->pays->Intitule}}"  class="span8" style="width: 50%">
        </div>
        @error('nompays') <span class="text-danger">{{ $errors->first('nompays') }}</span> @enderror
        <span class="focus-input100"></span>
    </div>
    <div class="control-group">
        <label class="control-label" for="basicinput">Action FM</label>
        <div class="controls">
            <input type="text" name="actionfm" id="basicinput" value="{{$listClub->ActionFM}}"  class="span8" style="width: 50%">
            <span class="help-inline">Maximum 50 caractères</span>
        </div>
        @error('nomclub') <span class="text-danger">{{ $errors->first('nomclub') }}</span> @enderror
        <span class="focus-input100"></span>
    </div>


    <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn" style="background: greenyellow">Valider</button>
        </div>
    </div>
</form>
<script>

</script>
@endsection