routes/web.php
<?php

use App\Http\Controllers\Bienvenu;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\participant;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\presentation;
use App\Http\Controllers\verification;
use App\Http\Controllers\renduassemble;
use App\Http\Controllers\ClubController;
use App\Http\Controllers\FraisController;
use App\Http\Controllers\AspectController;
use App\Http\Controllers\PaiementController;
use App\Http\Controllers\PersonneController;
use App\Http\Controllers\EvenementController;
use App\Http\Controllers\TableUserController;
use App\Http\Controllers\StatutUserController;
use App\Http\Controllers\AjoutMembreController;
use App\Http\Controllers\PerformanceController;
use App\Http\Controllers\AnneeRotarienneController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/* Route::get('/', function () {
    return view('welcomeadmin');
}); */

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('statut-user', StatutUserController::class);

//Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

//User
Route::get('/ajoutMembre', [AjoutMembreController::class, 'indexAjoutMembre'])->name('ajoutMembreVue')->middleware('auth');
Route::post('/ajoutMembre',[AjoutMembreController::class, 'ajoutMembre'])->name('ajoutMembre');

Route::get('/tableUser', [TableUserController::class, 'indexTableUser'])->name('indextableUser')->middleware('auth');
Route::put('/supprimerUser/{id}', [TableUserController::class, 'supprimerUser'])->name('supprimerUser');
Route::post('/supprimerUserAll', [TableUserController::class, 'supprimerUserAll'])->name('supprimerUserAll');
Route::post('/supprimerUserAllCocher', [TableUserController::class, 'supprimerUserAllCocher'])->name('supprimerUserAllCocher');
Route::post('/retourAjouter', [TableUserController::class, 'retourAjouter'])->name('retourAjouter');
Route::post('/compteRenduReunion', [TableUserController::class, 'compteRenduReunion'])->name('compteRenduReunion');

Route::get('/evenementPublication', [EvenementController::class, 'evenement'])->name('evenement')->middleware('auth');
Route::post('/evenementPublication', [EvenementController::class, 'evenementPublication'])->name('evenementPublication');

Route::get('/fraisParticipation', [FraisController::class, 'fraisParticipation'])->name('fraisParticipation')->middleware('auth');
Route::post('/fraisParticipation', [FraisController::class, 'ValidationFraisParticipation'])->name('ValidationFraisParticipation');
Route::get('/paiement',[PaiementController::class, 'paiement'])->name('paiement');


//
Route::get('bienvenue', [Bienvenu::class, 'bienvenue']);
Route::get('create', [Bienvenu::class, 'frais']);
//Route::resource('frais', FraisController::class);
Route::resource('statut-user', StatutUserController::class)->middleware('auth');
Route::get('bienvenue', [Bienvenu::class, 'bienvenue'])->name('bienvenue')->middleware('auth');
Route::get('create', [Bienvenu::class, 'frais'])->middleware('auth');
//Route::resource('frais', FraisController::class)->middleware('auth');
Route::resource('frais', FraisController::class)->middleware('auth');
Route::post('personne/connexion', [PersonneController::class, 'verification'])->name('loginconnexion');
Route::resource('personne', PersonneController::class)/* ->middleware('auth') */;
Route::get('personne/desable/{id}', [PersonneController::class, 'disable'])->name('person.desable')->middleware('auth');
Route::resource('club', ClubController::class)/* ->middleware('auth') */;
Route::resource('anneerotarienne', AnneeRotarienneController::class)->middleware('auth');
Route::resource('performance', PerformanceController::class)->middleware('auth');
Route::resource('aspect', AspectController::class)->middleware('auth');
Route::get('rotary', [presentation::class, 'rotary']);
Route::get('interact', [presentation::class, 'interact']);
Route::get('district9102', [presentation::class, 'district9102']);
Route::get('ryla', [presentation::class, 'ryla']);
Route::get('acd', [presentation::class, 'acd']);
Route::post('seconnecter', [verification::class, 'verification'])->name('seconnecter');
Route::get('compterenduassemble', [renduassemble::class, 'create']);
Route::get('personnepresente', [participant::class, 'create']);

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Company Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{{asset('Company/assets/img/favicon.png')}}" rel="icon">
  <link href="{{asset('Company/assets/img/apple-touch-icon.png')}}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{{asset('Company/assets/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
  <link href="{{asset('Company/assets/vendor/icofont/icofont.min.css')}}" rel="stylesheet">
  <link href="{{asset('Company/assets/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
  <link href="{{asset('Company/assets/vendor/animate.css/animate.min.css')}}" rel="stylesheet">
  <link href="{{asset('Company/assets/vendor/venobox/venobox.css')}}" rel="stylesheet">
  <link href="{{asset('Company/assets/vendor/owl.carousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
  <link href="{{asset('Company/assets/vendor/aos/aos.css')}}" rel="stylesheet">
  <link href="{{asset('Company/assets/vendor/remixicon/remixicon.css')}}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{{asset('Company/assets/css/style.css')}}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Company - v2.2.0
  * Template URL: https://bootstrapmade.com/company-free-html-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo mr-auto"><a href="index.html"><span>Com</span>pany</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo mr-auto"><img src="{{asset('Company/assets/img/logo.png')}}" alt="" class="img-fluid"></a>-->

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="index.html">Home</a></li>

          <li class="drop-down"><a href="">About</a>
            <ul>
              <li><a href="about.html">About Us</a></li>
              <li><a href="team.html">Team</a></li>
              <li><a href="testimonials.html">Testimonials</a></li>
              <li class="drop-down"><a href="#">Deep Drop Down</a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
            </ul>
          </li>

          <li><a href="services.html">Services</a></li>
          <li><a href="portfolio.html">Portfolio</a></li>
          <li><a href="pricing.html">Pricing</a></li>
          <li><a href="blog.html">Blog</a></li>
          <li><a href="contact.html">Contact</a></li>

        </ul>
      </nav><!-- .nav-menu -->

      <div class="header-social-links">
        <a href="#" class="twitter"><i class="icofont-twitter"></i></a>
        <a href="#" class="facebook"><i class="icofont-facebook"></i></a>
        <a href="#" class="instagram"><i class="icofont-instagram"></i></a>
        <a href="#" class="linkedin"><i class="icofont-linkedin"></i></i></a>
      </div>

    </div>
  </header><!-- End Header -->

<section>
    @yield('content')
</section>

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Company</h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="mr-md-auto text-center text-md-left">
        <div class="copyright">
          &copy; Copyright <strong><span>Company</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/company-free-html-bootstrap-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

  <!-- Vendor JS Files -->
  <script src="{{asset('Company/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('Company/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  <script src="{{asset('Company/assets/vendor/jquery.easing/jquery.easing.min.js')}}"></script>
  <script src="{{asset('Company/assets/vendor/php-email-form/validate.js')}}"></script>
  <script src="{{asset('Company/assets/vendor/jquery-sticky/jquery.sticky.js')}}"></script>
  <script src="{{asset('Company/assets/vendor/isotope-layout/isotope.pkgd.min.js')}}"></script>
  <script src="{{asset('Company/assets/vendor/venobox/venobox.min.js')}}"></script>
  <script src="{{asset('Company/assets/vendor/waypoints/jquery.waypoints.min.js')}}"></script>
  <script src="{{asset('Company/assets/vendor/owl.carousel/owl.carousel.min.js')}}"></script>
  <script src="{{asset('Company/assets/vendor/aos/aos.js')}}"></script>

  <!-- Template Main JS File -->
  <script src="{{asset('Company/assets/js/main.js')}}"></script>
@yield('js')
</body>

</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif
                            
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/dashboard.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Edmin</title>
        <link type="text/css" href="{{asset('Edmin/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
        <link type="text/css" href="{{asset('Edmin/bootstrap/css/bootstrap-responsive.min.css')}}" rel="stylesheet">
        <link type="text/css" href="{{asset('Edmin/css/theme.css')}}" rel="stylesheet">
        <link type="text/css" href="{{asset('Edmin/css/Mes-Css/form.css')}}" rel="stylesheet">
        <link type="text/css" href="{{asset('Edmin/images/icons/css/font-awesome.css')}}" rel="stylesheet">
        <link rel="stylesheet" href="{{ asset('Edmin/font-awesome/css/font-awesome.min.css') }}" type="text/css" />
        <link rel="stylesheet" href="{{ asset('Edmin/select2-bootstrap.min.css') }}" type="text/css" />
        <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
            rel='stylesheet'>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>

<body>
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                    <i class="icon-reorder shaded"></i></a><a class="brand" href="index.html">Edmin </a>
                <div class="nav-collapse collapse navbar-inverse-collapse">
                    <ul class="nav nav-icons">
                        <li class="active"><a href="#"><i class="icon-envelope"></i></a></li>
                        <li><a href="#"><i class="icon-eye-open"></i></a></li>
                        <li><a href="#"><i class="icon-bar-chart"></i></a></li>
                    </ul>
                    <form class="navbar-search pull-left input-append" action="#">
                        <input type="text" class="span3">
                        <button class="btn" type="button">
                            <i class="icon-search"></i>
                        </button>
                    </form>
                    <ul class="nav pull-right">
                        <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown
                                <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Item No. 1</a></li>
                                <li><a href="#">Don't Click</a></li>
                                <li class="divider"></li>
                                <li class="nav-header">Example Header</li>
                                <li><a href="#">A Separated link</a></li>
                            </ul>
                        </li>
                        <li><a href="#">Support </a></li>
                        <li class="nav-user dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="{{asset('Edmin/images/user.png')}}" class="nav-avatar" />
                                <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Your Profile</a></li>
                                <li><a href="#">Edit Profile</a></li>
                                <li><a href="#">Account Settings</a></li>
                                <li class="divider"></li>
                                <li>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Se déconnecter') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- /.nav-collapse -->
            </div>
        </div>
        <!-- /navbar-inner -->
    </div>
    <!-- /navbar -->
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="span3">
                    <div class="sidebar">
                        <ul class="widget widget-menu unstyled">
                            <li class="active"><a href="index.html"><i class="menu-icon icon-dashboard"></i>Dashboard
                                </a></li>
                            <li><a href="{{route('ajoutMembreVue')}}"><i class="menu-icon icon-bullhorn"></i>Ajout des
                                    membres</a>
                            </li>
                            <li><a href="{{route('evenement')}}"><i class="menu-icon icon-inbox"></i>Passer une annonce
                                    <b class="label green pull-right">
                                    </b> </a></li>
                            <li><a href="{{route('personne.create')}}"><i class="menu-icon icon-tasks"></i>Ajout de responsables <b
                                        class="label orange pull-right">
                                    </b> </a></li>
                        </ul>
                        <!--/.widget-nav-->


                        <ul class="widget widget-menu unstyled">
                            <li><a href="{{route('personne.index')}}"><i class="menu-icon icon-bold"></i> Liste des responsables
                                </a></li>
                            <li><a href="{{route('performance.create')}}"><i class="menu-icon icon-book"></i>Noter les clubs </a>
                            </li>
                            <li><a href="{{route('aspect.create')}}"><i class="menu-icon icon-paste"></i>Ajout des aspects </a></li>
                            <li><a href="{{route('performance.index')}}"><i class="menu-icon icon-table"></i>Voir les performances </a></li>
                            <li><a href="charts.html"><i class="menu-icon icon-bar-chart"></i>Les annonces </a></li>
                        </ul>
                        <!--/.widget-nav-->
                        <ul class="widget widget-menu unstyled">
                            <li><a class="collapsed" data-toggle="collapse" href="#togglePages"><i
                                        class="menu-icon icon-cog">
                                    </i><i class="icon-chevron-down pull-right"></i><i
                                        class="icon-chevron-up pull-right">
                                    </i>More Pages </a>
                                <ul id="togglePages" class="collapse unstyled">
                                    <li><a href="other-login.html"><i class="icon-inbox"></i>Ajout d'une personne </a>
                                    </li>
                                    <li><a href="other-user-profile.html"><i class="icon-inbox"></i>Ajout d'un club </a>
                                    </li>
                                    <li><a href="other-user-listing.html"><i class="icon-inbox"></i>Ajout d'une
                                            performance </a></li>
                                </ul>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i
                                        class="menu-icon icon-signout"></i>
                                    {{ __('Se déconnecter') }}
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!--/.sidebar-->
                </div>
                <!--/.span3-->
                <div class="span9">
                    <div class="content">
                        @yield('content')
                        <!--/.module-->
                    </div>
                    <!--/.content-->
                </div>
                <!--/.span9-->
            </div>
        </div>
        <!--/.container-->
    </div>
    <!--/.wrapper-->
    <div class="footer">
        <div class="container">
            <b class="copyright">&copy; 2014 Edmin - EGrappler.com </b>All rights reserved.
        </div>
        <script src="{{asset('Edmin/scripts/jquery-1.9.1.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('Edmin/scripts/jquery-ui-1.10.1.custom.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('Edmin/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
        <script src="{{asset('Edmin/scripts/flot/jquery.flot.js')}}" type="text/javascript"></script>
        <script src="{{asset('Edmin/scripts/flot/jquery.flot.resize.js')}}" type="text/javascript"></script>
        <script src="{{asset('Edmin/scripts/datatables/jquery.dataTables.js')}}" type="text/javascript"></script>
        <script src="{{asset('Edmin/scripts/common.js')}}" type="text/javascript"></script>
         <script src="{{asset('Edmin/scripts/Mes-Js/checkBox.js')}}"></script>
        @yield('js')
    </body>
    </div>
    <script>
        $(document).ready(function()
        {
            var sportslist =
            [
                "cricket", "volleyball", "rugby", "tennis", "baseball"
            ];
            $("#sports").select2({
                data:sportslist
            })
        });
    </script>
    <script src="{{asset('Edmin/jquery.min.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
    <script src="{{asset('Edmin/scripts/jquery-1.9.1.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('Edmin/scripts/jquery-ui-1.10.1.custom.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('Edmin/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
    <script src="{{asset('Edmin/scripts/flot/jquery.flot.js')}}" type="text/javascript"></script>
    <script src="{{asset('Edmin/scripts/flot/jquery.flot.resize.js')}}" type="text/javascript"></script>
    <script src="{{asset('Edmin/scripts/datatables/jquery.dataTables.js')}}" type="text/javascript"></script>
    <script src="{{asset('Edmin/scripts/common.js')}}" type="text/javascript"></script>
    @yield('js')
</body>